#Unit Labels
UNIT_MPH = 'mph'
UNIT_KPH = 'kph'
UNIT_FT = 'ft'
UNIT_M = 'm'
UNIT_IN = 'in'
UNIT_CM = 'cm'
UNIT_DEG = '°'
UNIT_DEG_F = '°F'
UNIT_DEG_C = '°C'
UNIT_GPA = 'gal/a'
UNIT_LPHA = 'l/ha'
UNIT_PSI = 'psi'
UNIT_BAR = 'bar'
UNIT_KPA = 'kpa'

#Unit Option Lists
UNITS_LENGTH_LARGE = [UNIT_FT, UNIT_M]
UNITS_LENGTH_SMALL = [UNIT_IN, UNIT_CM]
UNITS_GS = [UNIT_MPH, UNIT_KPH]
UNITS_SH = [UNIT_FT, UNIT_M]
UNITS_WS = [UNIT_MPH, UNIT_KPH]
UNITS_T = [UNIT_DEG_F, UNIT_DEG_C]
UNITS_RATE = [UNIT_GPA, UNIT_LPHA]
UNITS_PRESSURE = [UNIT_PSI, UNIT_BAR, UNIT_KPA]

# Math Conversion Constants
UM_PER_IN = 25400.0
FT_PER_M = 3.28084
MPH_PER_KPH = 0.621371
MPH_PER_KN = 1.15078

# Pattern Centering
CENTER_METHOD_NONE = -1
CENTER_METHOD_CENTROID = 0
CENTER_METHOD_COD = 1

# String Drive Commands
STRING_DRIVE_FWD_START = 'AD+\r'
STRING_DRIVE_FWD_STOP = 'AD\r'
STRING_DRIVE_REV_START = 'BD-\r'
STRING_DRIVE_REV_STOP = 'BD\r'

# Spectrometer
SPEC_WAV_EX_RHODAMINE = 525
SPEC_WAV_EM_RHODAMINE = 575
SPEC_WAV_EX__DEFAULT = SPEC_WAV_EX_RHODAMINE
SPEC_WAV_EM__DEFAULT = SPEC_WAV_EM_RHODAMINE
SPEC_INT_TIME_MS__DEFAULT = 100

# SprayCard DPI
DPI_OPTIONS = ['300','600','1200','2400']

# SprayCard Thresholding Constants
THRESHOLD_TYPE_GRAYSCALE = 'Grayscale'
THRESHOLD_TYPE_HSB = 'HSB'
THRESHOLD_TYPES = [THRESHOLD_TYPE_GRAYSCALE, THRESHOLD_TYPE_HSB]
THRESHOLD_TYPE__DEFAULT = THRESHOLD_TYPES[0]
# SprayCard Thresholding Constants (Grayscale)
THRESHOLD_GRAYSCALE__DEFAULT = 152
THRESHOLD_GRAYSCALE_METHOD_AUTO = 'Auto'
THRESHOLD_GRAYSCALE_METHOD_MANUAL = 'Manual'
THRESHOLD_GRAYSCALE_METHODS = [THRESHOLD_GRAYSCALE_METHOD_AUTO,THRESHOLD_GRAYSCALE_METHOD_MANUAL]
THRESHOLD_GRAYSCALE_METHOD__DEFAULT = THRESHOLD_GRAYSCALE_METHODS[0]
# SprayCard Thresholding Constants (HSB)
THRESHOLD_HSB_HUE__DEFAULT = (180,240)
THRESHOLD_HSB_SATURATION__DEFAULT = (6,255)
THRESHOLD_HSB_BRIGHTNESS__DEFAULT = (0,255)
THRESHOLD_HSB_METHOD_INCLUDE = 'Include'
THRESHOLD_HSB_METHOD_EXCLUDE = 'Exclude'
THRESHOLD_HSB_METHODS = [THRESHOLD_HSB_METHOD_INCLUDE,THRESHOLD_HSB_METHOD_EXCLUDE]
THRESHOLD_HSB_METHOD__DEFAULT = THRESHOLD_HSB_METHODS[1]

# SprayCard Processed Image Colors
COLOR_STAIN_OUTLINE = (138, 43, 226) #Red-Pink
COLOR_STAIN_FILL_ALL = (0, 0, 255) #Red
COLOR_STAIN_FILL_EDGE = (238, 130, 238) #Violet
COLOR_STAIN_FILL_VALID = (255, 0, 0) #Blue

# SprayCard Spread Factor Methods
SPREAD_FACTOR_A__DEFAULT = 0.0000
SPREAD_FACTOR_B__DEFAULT = 0.0009
SPREAD_FACTOR_C__DEFAULT = 1.6333
SPREAD_METHOD_NONE = 'None'
SPREAD_METHOD_DIRECT = 'Direct'
SPREAD_METHOD_ADAPTIVE = 'Adaptive'
SPREAD_METHODS = [SPREAD_METHOD_NONE,SPREAD_METHOD_DIRECT,SPREAD_METHOD_ADAPTIVE]
SPREAD_METHOD__DEFAULT = SPREAD_METHODS[2]

    
