"""Auto-discovers every sibling module's NOZZLE constant into NOZZLES.

Each per-nozzle file is generated by tools/extract_atomization_model.py and
exports a single `NOZZLE: Nozzle`. Adding a new file is enough to register it.
"""

from __future__ import annotations

import importlib
import pkgutil

from ..types import Nozzle

NOZZLES: dict[str, Nozzle] = {}

for _info in pkgutil.iter_modules(__path__):
    if _info.name.startswith("_"):
        continue
    _mod = importlib.import_module(f".{_info.name}", __name__)
    _nozzle = getattr(_mod, "NOZZLE", None)
    if isinstance(_nozzle, Nozzle):
        NOZZLES[_nozzle.name] = _nozzle
